#!/bin/sh
# Re-creates Sources/CStockfish/stockfish from an official Stockfish release
# tarball and applies the local patches in patches/ (in file name order).
#
# The vendored tree is generated by this script; do not hand-edit it. To change
# Stockfish's source, add or edit a patch in patches/ and re-run this script.
# To upgrade Stockfish, change SF_TAG and SF_TARBALL_SHA256 below, re-run this
# script, then run scripts/fetch-nets.sh (the network name can change).
#
# Usage: scripts/vendor-stockfish.sh
set -eu

SF_TAG="sf_19"
SF_TARBALL_SHA256="519b653d0d1ffb96531d982ccbe5c6a19425e8388e0e3c2f70f34b424ab32d76"
SF_URL="https://github.com/official-stockfish/Stockfish/archive/refs/tags/$SF_TAG.tar.gz"

PKG_DIR=$(cd "$(dirname "$0")/.." && pwd)
DEST="$PKG_DIR/Sources/CStockfish/stockfish"
WORK=$(mktemp -d "${TMPDIR:-/tmp}/vendor-stockfish.XXXXXX")
trap 'rm -rf "$WORK"' EXIT

echo "downloading $SF_URL"
curl -fsSL --retry 3 -o "$WORK/sf.tar.gz" "$SF_URL"
ACTUAL=$(shasum -a 256 "$WORK/sf.tar.gz" | cut -c 1-64)
if [ "$ACTUAL" != "$SF_TARBALL_SHA256" ]; then
  echo "error: tarball SHA-256 is $ACTUAL, expected $SF_TARBALL_SHA256" >&2
  exit 1
fi

tar -xzf "$WORK/sf.tar.gz" -C "$WORK"
SRC_ROOT=$(find "$WORK" -mindepth 1 -maxdepth 1 -type d -name 'Stockfish-*' | head -n 1)

rm -rf "$DEST"
mkdir -p "$DEST"
# Only what is needed to build plus the license and attribution files.
cp -R "$SRC_ROOT/src" "$DEST/src"
cp "$SRC_ROOT/Copying.txt" "$SRC_ROOT/AUTHORS" "$SRC_ROOT/README.md" "$DEST/"

for PATCH in "$PKG_DIR"/patches/*.patch; do
  [ -e "$PATCH" ] || continue
  echo "applying $(basename "$PATCH")"
  patch -d "$DEST" -p1 --forward --no-backup-if-mismatch <"$PATCH"
done

echo "$SF_TAG" >"$DEST/VENDORED_TAG"
echo "vendored Stockfish $SF_TAG into $DEST"
